apps/ves/urls.py
from django.contrib import admin
from django.urls import path
import asyncio
from apps.ves.catalog import CatalogAutoView, CatalogTrailerView, CatalogProductView
from apps.ves.views import StartView, DataView

app_name = 'ves'
urlpatterns = [
    path('',  StartView.as_view(), name = 'start'),
    path('ves',  StartView.menu_ves, name = 'menu_ves'),
    path('ves/avto',  StartView.avto_ves, name = 'avto_ves'),
    path('ves/avtodata',  StartView.avto_data, name = 'avto_data'),
    path('ves/zd',  StartView.zd_ves, name = 'zd_ves'),
    path('ves/zddata',  StartView.zd_data, name = 'zd_data'),
    # path('<str:room_name>/', views.room, name='room'),

    path('data',  DataView.menu_data, name = 'menu_data'),
    path('data/contragents',  DataView.AgentView, name = 'contragents'),
    path('data/actions',  DataView.ActionView, name = 'actions'),
    path('ves/users', DataView.UserView, name='users'),
    path('ves/users/<int:usid>/', DataView.updateUserView, name='usersUpd'),

    #catalog views
    path('data/catalog/auto',CatalogAutoView.showAuto,name='catalogAuto'),
    path('data/catalog/auto/addAuto',CatalogAutoView.addAuto,name='catalogAutoAdd'),
    path('data/catalog/auto/updAuto',CatalogAutoView.addUpdate,name='catalogAutoUpd'),

    path('data/catalog/trailer',CatalogTrailerView.showTrailer,name='catalogTrailer'),
    path('data/catalog/trailer/addTrailer',CatalogTrailerView.addTrailer,name='catalogTrailerAdd'),
    path('data/catalog/trailer/updTrailer',CatalogTrailerView.addUpdate,name='catalogTrailerUpd'),

    path('data/catalog/production', CatalogProductView.sowCatalog, name='catalogProduction'),
    path('data/catalog/production/addProduction', CatalogProductView.addProduction, name='catalogProductionAdd'),
    path('data/catalog/production/updProduction', CatalogTrailerView.addUpdate, name='catalogProductionUpd'),


]

ves_n/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.ves.add_in_db import addAutoNew, addVagonNew
from apps.ves.contract import showContract, AddContract, UpdContract, deleteContract
from apps.ves.detectNumber import detectNumber
from apps.ves.docGeneration import actGenerate
from apps.ves.production import showProduction, AddProduction, UpdProduction, deleteProduction
from apps.ves.responseblePerson import showPerson, AddPerson, UpdPerson, deletePerson
from apps.ves.trailer import showTrailer, UpdTrailer, AddTrailer, deleteTrailer
from ves_n.views import *

from channels.routing import ProtocolTypeRouter
from django.views.defaults import server_error, page_not_found, permission_denied
application = ProtocolTypeRouter({
    # Empty for now (http->django views is added by default)
})

urlpatterns = [
    path('', include('apps.ves.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout', logout_view, name = 'logout'),
    path('addaction/',addactionView, name='addaction'),

    path('addvagonPOST/',addVagonPost, name='addVagonPOST'),
    path('addcontragentPOST/',addContragentView, name='addcontragentPOST'),
    path('updcontragentPOST/',updContragentView, name='updcontragentPOST'),
    path('getDataAuto/', GetDataAuto, name='getDataAuto'),
    path('getDataZd/', GetDataZd, name='getDataZd'),
    path('getDataStatus/', GetDataStatus, name='getDataStatus'),
    path('getDataZd/getzdnumbler', GetZdNumber, name='getZdNumber'),
    path('getDataZd/getzdagent', GetZdAgent, name='getZdAgent'),
    path('getDataZd/getzddate', GetZdDate, name='getZdDate'),

    path('getDataAuto/getautonumbler', GetAutoNumber, name='getAutoNumber'),
    path('getDataAuto/getautoagent', GetAutoAgent, name='getAutoAgent'),
    path('getDataAuto/getautodate', GetAutoDate, name='getAutoDate'),

    path('onoff/svet1/',onOffS1,name='on1'),
    path('onoff/zd/svet1/',onOffZd,name='onoffzd'),
    path('add/auto/new',addAutoNew,name='newAddAuto'),
    path('add/train/new',addVagonNew,name='newAddVagon'),
    path('detect/auto/number', detectNumber, name='detectNumber'),

    #данные бд контрагент
    path('data/catalogContract',showContract,name='catalogcontract'),
    path('data/catalogContractAdd',AddContract,name='catalogcontractAdd'),
    path('data/catalogContractUpd',UpdContract,name='catalogcontractUpd'),
    path('data/catalogContractDel', deleteContract, name='catalogcontractDel'),

    # прицепы
    path('data/trailerShow',showTrailer,name='trailerShow'),
    path('data/trailerAdd',AddTrailer,name='trailerAdd'),
    path('data/trailerUpd',UpdTrailer,name='trailerUpd'),
    path('data/trailerDel', deleteTrailer, name='trailerDel'),
    # дукция
    path('data/productionShow', showProduction, name='productionShow'),
    path('data/productionAdd', AddProduction, name='productionAdd'),
    path('data/productionUpd', UpdProduction, name='productionUpd'),
    path('data/productionDel', deleteProduction, name='productionDel'),
    # отвественные лица
    path('data/personShow', showPerson, name='personShow'),
    path('data/personAdd', AddPerson, name='personAdd'),
    path('data/personUpd', UpdPerson, name='personnUpd'),
    path('data/personDel', deletePerson, name='personDel'),

    #отчеты
    path('reportAutoAgent/get', reportAutoAgent, name='reportAutoAgent'),
    path('act/generate/get', actGenerate, name='actGenerate'),

    path('search/', serchAuto, name='search'),
]

templates/data/action_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {#  <link rel="stylesheet" href="{% static 'css/Article-List.css' %}">#}
        <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome-all.min.css' %}">
{#        <link rel="stylesheet" href="{% static 'css/Features-Boxed.css' %}">#}
        <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
{#        <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
        <link rel="stylesheet" href="{% static 'css/table-css.css' %}">
{#       <script src="{% static 'js/all.js' %}"></script>#}
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <script src="{% static 'js/table-equipment.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>

<h4 style="position: absolute; top: 15px; left: 22%;color:#adb7b7;">События</h4>
{#  <div class="container">#}
{#    {% for contact in page_obj %}#}
    {# Each "contact" is a Contact model object. #}
{#    {{ contact.action|upper }} - {{ contact.where|upper }} - {{ contact.parentId.username }} :: {{ contact.date_add|upper }}#}
{#        <hr>#}
{#    ...#}
{#{% endfor %}#}

{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page=1">&laquo; first</a>#}
{#            <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">next</a>#}
{#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}
{##}
{#  </div>#}

    <div class="container-fluid" style="padding-top: 20px;">
        <div class="row">
            <div class="col-12" id="otchetTableContragent"><div class="wrapper-modal-editor">

                <table id="editibleTable" class="table table-bordered table-hover table-sm text-center" cellspacing="0" width="100%">
  <thead>
    <tr>
         <th class="th-sm">Действие</th>
      <th class="th-sm">Где</th>
      <th class="th-sm">Пользователь</th>
        <th class="th-sm">Дата</th>

    </tr>
  </thead>
  <tbody>

{#  {% for contact in page_obj %}#}
    {# Each "contact" is a Contact model object. #}
{#    {{ contact.action|upper }} - {{ contact.where|upper }} - {{ contact.parentId.username }} :: {{ contact.date_add|upper }}#}
{#        <hr>#}
{#    ...#}
{#{% endfor %}#}



  {% for contact in page_obj %}
    <tr>
     <td>{{ contact.action|upper }}</td>
      <td>{{ contact.where|upper }}</td>
      <td>{{ contact.parentId.username }}</td>
         <td>{{ contact.date_add|upper }}</td>
    </tr>
  {% endfor %}


  </tbody>
	<tfoot>
		<tr>
        <th >Действие</th>
      <th >Где</th>
      <th >Пользователь</th>
        <th >Дата</th>
			</tr>
      </tfoot>
</table>


	</div>
        </div>
    </div>
    </div>


    <script src="{% static 'popper.js' %}" ></script>
<script src="{% static 'b.min.js' %}" ></script>


{#   запрет на выделение обычного текста #}
    <script>
    function preventSelection(element){
            var preventSelection = false;

        function addHandler(element, event, handler){
         if (element.attachEvent)
      element.attachEvent('on' + event, handler);
    else
      if (element.addEventListener)
        element.addEventListener(event, handler, false);
  }
  function removeSelection(){
    if (window.getSelection) { window.getSelection().removeAllRanges(); }
    else if (document.selection && document.selection.clear)
      document.selection.clear();
  }
  function killCtrlA(event){
    var event = event || window.event;
    var sender = event.target || event.srcElement;

    if (sender.tagName.match(/INPUT|TEXTAREA/i))
      return;

    var key = event.keyCode || event.which;
    if (event.ctrlKey && key == 'A'.charCodeAt(0))  // 'A'.charCodeAt(0) можно заменить на 65
    {
      removeSelection();

      if (event.preventDefault)
        event.preventDefault();
      else
        event.returnValue = false;
    }
  }

  // не даем выделять текст мышкой
  addHandler(element, 'mousemove', function(){
    if(preventSelection)
      removeSelection();
  });
  addHandler(element, 'mousedown', function(event){
    var event = event || window.event;
    var sender = event.target || event.srcElement;
    preventSelection = !sender.tagName.match(/INPUT|TEXTAREA/i);
  });

  // борем dblclick
  // если вешать функцию не на событие dblclick, можно избежать
  // временное выделение текста в некоторых браузерах
  addHandler(element, 'mouseup', function(){
    if (preventSelection)
      removeSelection();
    preventSelection = false;
  });

  // борем ctrl+A
  // скорей всего это и не надо, к тому же есть подозрение
  // что в случае все же такой необходимости функцию нужно
  // вешать один раз и на document, а не на элемент
  addHandler(element, 'keydown', killCtrlA);
  addHandler(element, 'keyup', killCtrlA);
}

$(document).ready ( function(){
 preventSelection(document);
});
    </script>

{% endblock %}

templates/data/catalog_production.html
{% extends 'base.html' %}
{% block title %}Каталог автотрансопрта{% endblock %}
{% load static %}
{% block content %}
  <link rel="stylesheet" href="{% static 'css/Article-List.css' %}">
        <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/Features-Boxed.css' %}">
        <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'css/table-css.css' %}">
       <script src="{% static 'js/all.js' %}"></script>
    <script src="{% static 'js/datatables.min.js' %}"></script>
    <script src="{% static 'js/table-equipment.js' %}"></script>
    <script src="{% static 'js/mdb.min.js' %}"></script>


  <!-- End: Navigation with Button -->
    <div class="container-fluid" style="padding-top: 20px;">
        <div class="row">
            <div class="col-12" id="otchetTableContragent"><div class="wrapper-modal-editor">

   <div class="row d-flex justify-content-center modalWrapper">
    <div class="modal fade addNewInputs" id="modalAdd" tabindex="-1" role="dialog" aria-labelledby="modalAdd"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold text-primary ml-5">Добавить продукцию</h4>
            <button type="button" class="close text-primary" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mx-3">

              <div class="md-form mb-5">
              <input type="text" id="number" class="form-control validate">
              <label data-error="измените" data-success="принято" for="number">номер продукции</label>
            </div>

		    <div class="md-form mb-5">
              <input type="text" id="name" class="form-control validate">
              <label data-error="измените" data-success="принято" for="model">наименование</label>
            </div>

          </div>
          <div class="modal-footer d-flex justify-content-center buttonAddFormWrapper">
            <button class="btn btn-outline-primary btn-block buttonAdd"  onclick="addAuto()" data-dismiss="modal">Добавить
              <i class="fas fa-paper-plane-o ml-1"></i>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center">
      <a href="" class="btn btn-info btn-rounded btn-sm" data-toggle="modal" data-target="#modalAdd">Добавить<i
          class="fas fa-plus-square ml-1"></i></a>
    </div>

    <div class="modal fade modalEditClass" id="modalEdit" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold text-secondary ml-5">Изменить</h4>
            <button type="button" class="close text-secondary" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
           <div class="modal-body mx-3">

              <div class="md-form mb-5">
              <input type="text" id="number_upd" class="form-control validate">
              <label data-error="измените" data-success="принято" for="number">номер прицепа</label>
            </div>

		    <div class="md-form mb-5">
              <input type="text" id="model_upd" class="form-control validate">
              <label data-error="измените" data-success="принято" for="model">модель и серия прицепа</label>
            </div>


		     <div class="md-form mb-5">
              <input type="text" id="tara_upd" class="form-control validate">
              <label data-success="принято" for="tara">Вес тара</label>
            </div>


          </div>
          <div class="modal-footer d-flex justify-content-center editInsideWrapper">
            <button onclick="updAuto()" class="btn btn-outline-secondary btn-block editInside" data-dismiss="modal">Изменить
              <i class="fas fa-paper-plane-o ml-1"></i>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center buttonEditWrapper">
      <button class="btn btn-info btn-rounded btn-sm buttonEdit" data-toggle="modal" data-target="#modalEdit"
        disabled>Изменить<i class="fas fa-pencil-square-o ml-1"></i></button>
    </div>

    <div class="modal fade" id="modalDelete" tabindex="-1" role="dialog" aria-labelledby="modalDelete"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold ml-5 text-danger">Удалить</h4>
            <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mx-3">
            <p class="text-center h4">Вы уверены что хотите удалить выбранного контрагента?</p>

          </div>
          <div class="modal-footer d-flex justify-content-center deleteButtonsWrapper">
            <button type="button" class="btn btn-danger btnYesClass" id="btnYes" data-dismiss="modal">Да</button>
            <button type="button" class="btn btn-primary btnNoClass" id="btnNo" data-dismiss="modal">Нет</button>
          </div>
        </div>
      </div>
    </div>

    <div class="text-center">
      <button class="btn btn-danger btn-sm btn-rounded buttonDelete" data-toggle="modal" disabled data-target="#modalDelete"
        disabled>Удалить<i class="fas fa-times ml-1"></i></button>
    </div>
  </div>

<table id="editibleTable" class="table table-bordered table-hover table-sm text-center" cellspacing="0" width="100%">
  <thead>
    <tr>
         <th class="th-sm">id</th>
      <th class="th-sm">название</th>
      <th class="th-sm">номер</th>
        <th class="th-sm">дата добавления</th>

    </tr>
  </thead>
  <tbody>
  {% for a in catalog %}
    <tr>
     <td>{{ a.id }}</td>
      <td>{{ a.name }}</td>
      <td>{{ a.number }}</td>

      <td>{{ a.date_add }}</td>
    </tr>
  {% endfor %}


  </tbody>
	<tfoot>
		<tr>
   <th >id</th>
      <th >название</th>
      <th >номер</th>
      <th >дата добавления</th>
			</tr>
      </tfoot>
</table>


	</div>
        </div>
    </div>


<script>
    function addAuto() {

        let number = $('#number').val();
        let model = $("#name").val();

        let data={
            'number':number,
            'name':model,
        };
        $.ajax({
                type: "POST",
                url: '{% url 'ves:catalogProductionAdd' %}',
                traditional: true,
                dataType: 'json',
                data: data,
                success: function (dat) {
                    console.log("auto added");
                },
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
    }

    function updAuto() {
        let id = $("#auto_id").val();
        let agent = $("#contragent_upd").val();
        let number = $('#number_upd').val();
        let model = $("#model_upd").val();
        let ves = $("#tara_upd").val();
        let data={
            'id':id,
            'agent':agent,
            'number':number,
            'model':model,
            'ves':ves
        };
        $.ajax({
                type: "POST",
                url: '{% url 'ves:catalogProductionUpd' %}',
                traditional: true,
                dataType: 'json',
                data: data,
                success: function (dat) {
                    console.log("production added");
                },
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
    }
</script>



     {% endblock %}

templates/data/menu_data.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <link rel="stylesheet" href="{% static 'boostrap/css/bootstrap.min.css' %}">
{#  <link rel="stylesheet" href="{% static 'css/Article-List.css' %}">#}
{#        <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">#}
        <link rel="stylesheet" href="{% static 'css/Features-Boxed.css' %}">
{#        <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">#}
{#        <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
{#        <link rel="stylesheet" href="{% static 'css/table-css.css' %}">#}
    <script src="{% static 'boostrap/js/bootstrap.min.js' %}"></script>
  <!-- End: Navigation with Button -->
    <!-- Start: Features Boxed -->
    <div class="features-boxed" style="background-color: rgb(255,255,255);">
        <div class="container">
            <!-- Start: Features -->
            <div  class="row justify-content-center features">
                <div onclick="gotoaddAgent()" class="col-sm-12 col-md-4 col-lg-4 col-xl-4 item" style="padding: 10px 15px;">
                    <div class="box" style="padding: 0px;"><img src="{% static 'img/img/conteragent.svg' %}" style="width: 260px;padding-top: 20px;">
                        <h3 class="name">Контрагенты</h3>
                        <p class="description" style="padding-bottom: 20px;">Добавление и редактирование списков контрагентов</p>
                    </div>
                </div>
                <div onclick="gotoViewActions()" class="col-sm-12 col-md-4 col-lg-4 col-xl-4 item" style="padding: 10px 15px;">
                    <div class="box" style="padding: 0px;"><img src="{% static 'img/img/magazine.svg' %}" style="width: 260px;padding-top: 20px;">
                        <h3 class="name">Журнал событий</h3>
                        <p class="description" style="padding-bottom: 20px;">Журнал действий пользователя, зарегистрированных в системе</p>
                    </div>
                </div>


                 <div onclick="gotoUserAdd()" class="col-sm-12 col-md-4 col-lg-4 col-xl-4 item" style="padding: 10px 15px;">
                    <div class="box" style="padding: 0px;"><img src="{% static 'img/img/users.svg' %}" style="width: 260px;padding-top: 20px;">
                        <h3 class="name">Журнал пользователей</h3>
                        <p class="description" style="padding-bottom: 20px;">Журнал пользователей. Добавление, удаление, редактирование пользователей системы.</p>
                    </div>
                 </div>
{#                      <div onclick="gotoEventSys()" class="col-sm-12 col-md-4 col-lg-4 col-xl-4 item" style="padding: 10px 15px;">#}
{#                    <div class="box" style="padding: 0px;"><img src="{% static 'img/img/systemEvent.svg' %}" style="width: 260px;padding-top: 20px;">#}
{#                        <h3 class="name">Журнал системных сообщений</h3>#}
{#                        <p class="description" style="padding-bottom: 20px;">Журнал системных сообщений. Просмотр сообщений ситемы. Бд системы.</p>#}
{#                    </div>#}
{#                </div>#}

                <div onclick="gotoaddAgent()" class="col-sm-12 col-md-4 col-lg-4 col-xl-4 item" style="padding: 10px 15px;">
                    <div class="box" style="padding: 0px;"><img src="{% static 'img/img/catalogAuto.svg' %}" style="width: 260px;padding-top: 20px;">
                        <h3 class="name">Каталог автотранспорта</h3>
                        <p class="description" style="padding-bottom: 20px;">Добавление и редактирование списков автотранспорта</p>
                    </div>
                </div>

                <div onclick="catalogProduction()" class="col-sm-12 col-md-4 col-lg-4 col-xl-4 item" style="padding: 10px 15px;">
                    <div class="box" style="padding: 0px;"><img src="{% static 'img/img/catalogGlass.svg' %}" style="width: 260px;padding-top: 20px;">
                        <h3 class="name">Каталог продукции</h3>
                        <p class="description" style="padding-bottom: 20px;">Добавление и редактирование списков продукции</p>
                    </div>
                </div>

            </div>
            <!-- End: Features -->
        </div>
    </div>
    <!-- End: Features Boxed -->
    <script src="{% static 'popper.js' %}" ></script>
<script src="{% static 'b.min.js' %}" ></script>


        <style>
    .menu:hover {
  -webkit-transform: scale(1.05);
  -ms-transform: scale(1.05);
  transform: scale(1.05);
}
</style>

    <script>
function gotoaddAgent() {
    window.location.href = "{% url 'ves:contragents' %}";
}
function gotoViewActions() {
    window.location.href = "{% url 'ves:actions' %}";
}
function gotoUserAdd() {
window.location.href = "{% url 'ves:users' %}";
}
function gotoEventSys() {
window.location.href = "{% url 'ves:users' %}";
}
function catalogProduction(){
window.location.href = "{% url 'ves:catalogProduction' %}";
}
    </script>

{% endblock %}