apps/ves/urls.py
from django.contrib import admin
from django.urls import path
import asyncio
from apps.ves.catalog import CatalogAutoView, CatalogTrailerView, CatalogProductView
from apps.ves.views import StartView, DataView

app_name = 'ves'
urlpatterns = [
    path('',  StartView.as_view(), name = 'start'),
    path('ves',  StartView.menu_ves, name = 'menu_ves'),
    path('ves/avto',  StartView.avto_ves, name = 'avto_ves'),
    path('ves/avtodata',  StartView.avto_data, name = 'avto_data'),
    path('ves/zd',  StartView.zd_ves, name = 'zd_ves'),
    path('ves/zddata',  StartView.zd_data, name = 'zd_data'),
    # path('<str:room_name>/', views.room, name='room'),

    path('data',  DataView.menu_data, name = 'menu_data'),
    path('data/contragents',  DataView.AgentView, name = 'contragents'),
    path('data/actions',  DataView.ActionView, name = 'actions'),
    path('ves/users', DataView.UserView, name='users'),
    path('ves/users/<int:usid>/', DataView.updateUserView, name='usersUpd'),

    #catalog views
    path('data/catalog/auto',CatalogAutoView.showAuto,name='catalogAuto'),
    path('data/catalog/auto/addAuto',CatalogAutoView.addAuto,name='catalogAutoAdd'),
    path('data/catalog/auto/updAuto',CatalogAutoView.addUpdate,name='catalogAutoUpd'),

    path('data/catalog/trailer',CatalogTrailerView.showTrailer,name='catalogTrailer'),
    path('data/catalog/trailer/addTrailer',CatalogTrailerView.addTrailer,name='catalogTrailerAdd'),
    path('data/catalog/trailer/updTrailer',CatalogTrailerView.addUpdate,name='catalogTrailerUpd'),

    path('data/catalog/production', CatalogProductView.sowCatalog, name='catalogProduction'),
    path('data/catalog/production/addProduction', CatalogProductView.addProduction, name='catalogProductionAdd'),
    path('data/catalog/production/updProduction', CatalogTrailerView.addUpdate, name='catalogProductionUpd'),


]

ves_n/urls.py
from django.contrib import admin
from django.urls import path, include

from apps.ves.add_in_db import addAutoNew, addVagonNew
from apps.ves.contract import showContract, AddContract, UpdContract, deleteContract
from apps.ves.detectNumber import detectNumber
from apps.ves.docGeneration import actGenerate
from apps.ves.production import showProduction, AddProduction, UpdProduction, deleteProduction
from apps.ves.responseblePerson import showPerson, AddPerson, UpdPerson, deletePerson
from apps.ves.trailer import showTrailer, UpdTrailer, AddTrailer, deleteTrailer
from ves_n.views import *

from channels.routing import ProtocolTypeRouter
from django.views.defaults import server_error, page_not_found, permission_denied
application = ProtocolTypeRouter({
    # Empty for now (http->django views is added by default)
})

urlpatterns = [
    path('', include('apps.ves.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout', logout_view, name = 'logout'),
    path('addaction/',addactionView, name='addaction'),

    path('addvagonPOST/',addVagonPost, name='addVagonPOST'),
    path('addcontragentPOST/',addContragentView, name='addcontragentPOST'),
    path('updcontragentPOST/',updContragentView, name='updcontragentPOST'),
    path('getDataAuto/', GetDataAuto, name='getDataAuto'),
    path('getDataZd/', GetDataZd, name='getDataZd'),
    path('getDataStatus/', GetDataStatus, name='getDataStatus'),
    path('getDataZd/getzdnumbler', GetZdNumber, name='getZdNumber'),
    path('getDataZd/getzdagent', GetZdAgent, name='getZdAgent'),
    path('getDataZd/getzddate', GetZdDate, name='getZdDate'),

    path('getDataAuto/getautonumbler', GetAutoNumber, name='getAutoNumber'),
    path('getDataAuto/getautoagent', GetAutoAgent, name='getAutoAgent'),
    path('getDataAuto/getautodate', GetAutoDate, name='getAutoDate'),

    path('onoff/svet1/',onOffS1,name='on1'),
    path('onoff/zd/svet1/',onOffZd,name='onoffzd'),
    path('add/auto/new',addAutoNew,name='newAddAuto'),
    path('add/train/new',addVagonNew,name='newAddVagon'),
    path('detect/auto/number', detectNumber, name='detectNumber'),

    #данные бд контрагент
    path('data/catalogContract',showContract,name='catalogcontract'),
    path('data/catalogContractAdd',AddContract,name='catalogcontractAdd'),
    path('data/catalogContractUpd',UpdContract,name='catalogcontractUpd'),
    path('data/catalogContractDel', deleteContract, name='catalogcontractDel'),

    # прицепы
    path('data/trailerShow',showTrailer,name='trailerShow'),
    path('data/trailerAdd',AddTrailer,name='trailerAdd'),
    path('data/trailerUpd',UpdTrailer,name='trailerUpd'),
    path('data/trailerDel', deleteTrailer, name='trailerDel'),
    # дукция
    path('data/productionShow', showProduction, name='productionShow'),
    path('data/productionAdd', AddProduction, name='productionAdd'),
    path('data/productionUpd', UpdProduction, name='productionUpd'),
    path('data/productionDel', deleteProduction, name='productionDel'),
    # отвественные лица
    path('data/personShow', showPerson, name='personShow'),
    path('data/personAdd', AddPerson, name='personAdd'),
    path('data/personUpd', UpdPerson, name='personnUpd'),
    path('data/personDel', deletePerson, name='personDel'),

    #отчеты
    path('reportAutoAgent/get', reportAutoAgent, name='reportAutoAgent'),
    path('act/generate/get', actGenerate, name='actGenerate'),

    path('search/', serchAuto, name='search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
{% load static %}
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} || System</title>
    <head>
   <link rel="stylesheet" href="{% static 'boostrap/css/bootstrap.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/Article-List.css' %}">

        <script src="{% static 'jq.js' %}"></script>
    <script src="{% static 'boostrap/js/bootstrap.min.js' %}"></script>
</head>
<body>

<style>
    .dropdown:hover > .dropdown-menu {
    display: block;
}
</style>

<header style="padding-bottom: 15px;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light ml-2 mr-2">
  <a class="navbar-brand" href="{% url 'ves:start' %}">Белресурсы</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-left: 20px;">
    <ul class="navbar-nav mr-auto">
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="{% url 'ves:start' %}">Стартовая <span class="sr-only">(current)</span></a>#}
{#      </li>#}


{#        <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'ves:menu_ves'  %}">Взвешивание</a>#}
{#      </li>#}

         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'ves:menu_ves' %}" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Взвешивание
        </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdown1">
{#            <a class="nav-link " href="{% url 'ves:menu_ves' %}">Меню</a>#}
            <a class="nav-link "   href="{% url 'ves:avto_ves' %}">Автотранспорт  <span id="automenu" class="badge badge-success">v</span></a>
            <a class="nav-link "  href="{% url 'ves:zd_ves' %}">Ж/Д транспорт <span id="zdmenu" class="badge badge-success">v</span></a>
            <a class="nav-link " href="{% url 'ves:avto_data' %}">Данные по авто</a>
            <a class="nav-link " href="{% url 'ves:zd_data' %}">Данные по Ж/Д</a>

        </div>
{#      </li>#}
{##}
{#        <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'ves:menu_data' %}">Данные</a>#}
{#      </li>#}


         <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'ves:menu_data' %}" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Данные
        </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdown2">
{#            <a class="nav-link " href="{% url 'ves:menu_data' %}">Меню</a>#}
              <a class="nav-link " href="{% url 'ves:contragents' %}">Контрагенты</a>
              <a class="nav-link " href="{% url 'ves:actions' %}">События</a>
            <a class="nav-link " href="{% url 'ves:users' %}">Пользователи</a>
            <a class="nav-link " href="{% url 'ves:catalogAuto' %}">Каталог автотранспорта</a>
            <a class="nav-link " href="{% url 'trailerShow' %}">Каталог прицепов</a>
            <a class="nav-link " href="{% url 'productionShow' %}">Каталог продукции</a>
             <a class="nav-link " href="{% url 'catalogcontract' %}">Каталог договоров</a>
            <a class="nav-link " href="{% url 'personShow' %}">Отвественные лица</a>
{#            <a class="nav-link " href="{% url 'ves:actions' %}">Сообщения</a>#}
        </div>
      </li>

{#        <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'ves:menu_ves' %}">Настройки</a>#}
{#      </li>#}

    </ul>

      <ul class="navbar-nav text-right mr-5" >
           <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ request.user    }}
        </a>
        <div class="dropdown-menu " aria-labelledby="navbarDropdown">

            <a class="nav-link " href="{%   url 'logout' %}">Выйти</a>

        </div>
      </li>

      </ul>



  </div>
</nav>


</header>

{% block content %}



{% endblock %}
   {% csrf_token %}

<script>
    $('.dropdown-toggle').click(function(e) {
    if ($(document).width() > 768) {
        e.preventDefault();
        let url = $(this).attr('href');
        if (url !== '#') {
            window.location.href = url;
        }
    }
});
</script>

<script src="{% static 'popper.js' %}" ></script>
<script src="{% static 'b.min.js' %}" ></script>
<script>


  var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }


    function falseAll(){
    let data ={"avto":false,"zd":false,"all":true};
              $.ajax({
                type: "POST",
                url: '{% url 'getDataAuto' %}',
                traditional: true,
                dataType: 'json',
                data: data,
                success: function (dat) {
                    console.log(dat);
                },
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
}
let statusGlobalJs;
   function getstatus(){
    let data ={"avto":false,"zd":false,"all":true};
              $.ajax({
                type: "POST",
                url: '{% url 'getDataStatus' %}',
                traditional: true,
                dataType: 'json',
                data: data,
                success: function (dat) {
                    statusGlobalJs=dat;
                    if(dat.auto) {
                        document.getElementById('automenu').classList.remove("badge-success");
                        document.getElementById('automenu').classList.add("badge-warning");
                    }else{
                        document.getElementById('automenu').classList.add("badge-success");
                        document.getElementById('automenu').classList.remove("badge-warning");
                bootstrap    }
                    if(dat.zd) {
                        document.getElementById('zdmenu').classList.remove("badge-success");
                        document.getElementById('zdmenu').classList.add("badge-warning");
                    }else{
                        document.getElementById('zdmenu').classList.add("badge-success");
                        document.getElementById('zdmenu').classList.remove("badge-warning");
                    }
                },
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
}
getstatus();
setTimeout(falseAll,2000);
setInterval(getstatus, 2000);
</script>
</body>
</html>